// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: v1/proto/hello.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_PLACEHOLDER Type = 0
	Type_PROSE       Type = 1
	Type_LYRICS      Type = 2
	Type_NOVEL       Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "PLACEHOLDER",
		1: "PROSE",
		2: "LYRICS",
		3: "NOVEL",
	}
	Type_value = map[string]int32{
		"PLACEHOLDER": 0,
		"PROSE":       1,
		"LYRICS":      2,
		"NOVEL":       3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_article_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_v1_proto_article_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_article_proto_rawDescGZIP(), []int{0}
}

//*
// 新建文章
type RequestCreateArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Author  string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	IsShow  bool   `protobuf:"varint,4,opt,name=is_show,json=isShow,proto3" json:"is_show,omitempty"`
	Type    Type   `protobuf:"varint,5,opt,name=type,proto3,enum=article.v1.Type" json:"type,omitempty"`
}

func (x *RequestCreateArticle) Reset() {
	*x = RequestCreateArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_article_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCreateArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateArticle) ProtoMessage() {}

func (x *RequestCreateArticle) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_article_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateArticle.ProtoReflect.Descriptor instead.
func (*RequestCreateArticle) Descriptor() ([]byte, []int) {
	return file_v1_proto_article_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCreateArticle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestCreateArticle) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RequestCreateArticle) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *RequestCreateArticle) GetIsShow() bool {
	if x != nil {
		return x.IsShow
	}
	return false
}

func (x *RequestCreateArticle) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_PLACEHOLDER
}

type ReplyCreateArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
}

func (x *ReplyCreateArticle) Reset() {
	*x = ReplyCreateArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_article_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyCreateArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCreateArticle) ProtoMessage() {}

func (x *ReplyCreateArticle) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_article_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCreateArticle.ProtoReflect.Descriptor instead.
func (*ReplyCreateArticle) Descriptor() ([]byte, []int) {
	return file_v1_proto_article_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyCreateArticle) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

//*
// 编辑文章
type RequestUpdateArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleId int64  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Author    string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	IsShow    bool   `protobuf:"varint,5,opt,name=is_show,json=isShow,proto3" json:"is_show,omitempty"`
	Type      Type   `protobuf:"varint,6,opt,name=type,proto3,enum=article.v1.Type" json:"type,omitempty"`
}

func (x *RequestUpdateArticle) Reset() {
	*x = RequestUpdateArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_article_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUpdateArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdateArticle) ProtoMessage() {}

func (x *RequestUpdateArticle) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_article_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdateArticle.ProtoReflect.Descriptor instead.
func (*RequestUpdateArticle) Descriptor() ([]byte, []int) {
	return file_v1_proto_article_proto_rawDescGZIP(), []int{2}
}

func (x *RequestUpdateArticle) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *RequestUpdateArticle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestUpdateArticle) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RequestUpdateArticle) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *RequestUpdateArticle) GetIsShow() bool {
	if x != nil {
		return x.IsShow
	}
	return false
}

func (x *RequestUpdateArticle) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_PLACEHOLDER
}

//*
// 删除文章
type RequestDeleteArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
}

func (x *RequestDeleteArticle) Reset() {
	*x = RequestDeleteArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_article_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDeleteArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeleteArticle) ProtoMessage() {}

func (x *RequestDeleteArticle) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_article_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeleteArticle.ProtoReflect.Descriptor instead.
func (*RequestDeleteArticle) Descriptor() ([]byte, []int) {
	return file_v1_proto_article_proto_rawDescGZIP(), []int{3}
}

func (x *RequestDeleteArticle) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

//*
// 查询文章
type RequestQueryArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleId int64 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
}

func (x *RequestQueryArticle) Reset() {
	*x = RequestQueryArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_article_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestQueryArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryArticle) ProtoMessage() {}

func (x *RequestQueryArticle) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_article_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQueryArticle.ProtoReflect.Descriptor instead.
func (*RequestQueryArticle) Descriptor() ([]byte, []int) {
	return file_v1_proto_article_proto_rawDescGZIP(), []int{4}
}

func (x *RequestQueryArticle) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type ReplyQueryArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleId int64  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Author    string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	IsShow    bool   `protobuf:"varint,5,opt,name=is_show,json=isShow,proto3" json:"is_show,omitempty"`
	Type      Type   `protobuf:"varint,6,opt,name=type,proto3,enum=article.v1.Type" json:"type,omitempty"`
}

func (x *ReplyQueryArticle) Reset() {
	*x = ReplyQueryArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_article_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyQueryArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyQueryArticle) ProtoMessage() {}

func (x *ReplyQueryArticle) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_article_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyQueryArticle.ProtoReflect.Descriptor instead.
func (*ReplyQueryArticle) Descriptor() ([]byte, []int) {
	return file_v1_proto_article_proto_rawDescGZIP(), []int{5}
}

func (x *ReplyQueryArticle) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *ReplyQueryArticle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReplyQueryArticle) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyQueryArticle) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ReplyQueryArticle) GetIsShow() bool {
	if x != nil {
		return x.IsShow
	}
	return false
}

func (x *ReplyQueryArticle) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_PLACEHOLDER
}

//*
// 文章列表
type RequestArticleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestArticleList) Reset() {
	*x = RequestArticleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_article_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestArticleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestArticleList) ProtoMessage() {}

func (x *RequestArticleList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_article_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestArticleList.ProtoReflect.Descriptor instead.
func (*RequestArticleList) Descriptor() ([]byte, []int) {
	return file_v1_proto_article_proto_rawDescGZIP(), []int{6}
}

type ReplyArticleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ArticleItem `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ReplyArticleList) Reset() {
	*x = ReplyArticleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_article_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyArticleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyArticleList) ProtoMessage() {}

func (x *ReplyArticleList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_article_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyArticleList.ProtoReflect.Descriptor instead.
func (*ReplyArticleList) Descriptor() ([]byte, []int) {
	return file_v1_proto_article_proto_rawDescGZIP(), []int{7}
}

func (x *ReplyArticleList) GetData() []*ArticleItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type ArticleItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleId int64  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Author    string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	IsShow    bool   `protobuf:"varint,5,opt,name=is_show,json=isShow,proto3" json:"is_show,omitempty"`
	Type      Type   `protobuf:"varint,6,opt,name=type,proto3,enum=article.v1.Type" json:"type,omitempty"`
}

func (x *ArticleItem) Reset() {
	*x = ArticleItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_article_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleItem) ProtoMessage() {}

func (x *ArticleItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_article_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleItem.ProtoReflect.Descriptor instead.
func (*ArticleItem) Descriptor() ([]byte, []int) {
	return file_v1_proto_article_proto_rawDescGZIP(), []int{8}
}

func (x *ArticleItem) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *ArticleItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleItem) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ArticleItem) GetIsShow() bool {
	if x != nil {
		return x.IsShow
	}
	return false
}

func (x *ArticleItem) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_PLACEHOLDER
}

var File_v1_proto_article_proto protoreflect.FileDescriptor

var file_v1_proto_article_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x24, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x33, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x6f,
	0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x68, 0x6f, 0x77, 0x12,
	0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x35, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x13,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x49, 0x64, 0x22, 0xb9, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12,
	0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x69, 0x73, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x14,
	0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x73, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x39, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x48, 0x4f, 0x4c, 0x44,
	0x45, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x52, 0x4f, 0x53, 0x45, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x4c, 0x59, 0x52, 0x49, 0x43, 0x53, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4e,
	0x4f, 0x56, 0x45, 0x4c, 0x10, 0x03, 0x32, 0x98, 0x03, 0x0a, 0x0e, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x20, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x1a, 0x1e, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x22, 0x00, 0x12, 0x4b,
	0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12,
	0x20, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x20, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x1a, 0x1d, 0x2e, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0b, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x1c, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x6f, 0x2d, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2f, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_proto_article_proto_rawDescOnce sync.Once
	file_v1_proto_article_proto_rawDescData = file_v1_proto_article_proto_rawDesc
)

func file_v1_proto_article_proto_rawDescGZIP() []byte {
	file_v1_proto_article_proto_rawDescOnce.Do(func() {
		file_v1_proto_article_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_proto_article_proto_rawDescData)
	})
	return file_v1_proto_article_proto_rawDescData
}

var file_v1_proto_article_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_proto_article_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_proto_article_proto_goTypes = []interface{}{
	(Type)(0),                    // 0: article.v1.Type
	(*RequestCreateArticle)(nil), // 1: article.v1.RequestCreateArticle
	(*ReplyCreateArticle)(nil),   // 2: article.v1.ReplyCreateArticle
	(*RequestUpdateArticle)(nil), // 3: article.v1.RequestUpdateArticle
	(*RequestDeleteArticle)(nil), // 4: article.v1.RequestDeleteArticle
	(*RequestQueryArticle)(nil),  // 5: article.v1.RequestQueryArticle
	(*ReplyQueryArticle)(nil),    // 6: article.v1.ReplyQueryArticle
	(*RequestArticleList)(nil),   // 7: article.v1.RequestArticleList
	(*ReplyArticleList)(nil),     // 8: article.v1.ReplyArticleList
	(*ArticleItem)(nil),          // 9: article.v1.ArticleItem
	(*emptypb.Empty)(nil),        // 10: google.protobuf.Empty
}
var file_v1_proto_article_proto_depIdxs = []int32{
	0,  // 0: article.v1.RequestCreateArticle.type:type_name -> article.v1.Type
	0,  // 1: article.v1.RequestUpdateArticle.type:type_name -> article.v1.Type
	0,  // 2: article.v1.ReplyQueryArticle.type:type_name -> article.v1.Type
	9,  // 3: article.v1.ReplyArticleList.data:type_name -> article.v1.ArticleItem
	0,  // 4: article.v1.ArticleItem.type:type_name -> article.v1.Type
	1,  // 5: article.v1.ArticleService.CreateArticle:input_type -> article.v1.RequestCreateArticle
	3,  // 6: article.v1.ArticleService.UpdateArticle:input_type -> article.v1.RequestUpdateArticle
	4,  // 7: article.v1.ArticleService.DeleteArticle:input_type -> article.v1.RequestDeleteArticle
	5,  // 8: article.v1.ArticleService.QueryArticle:input_type -> article.v1.RequestQueryArticle
	10, // 9: article.v1.ArticleService.ArticleList:input_type -> google.protobuf.Empty
	2,  // 10: article.v1.ArticleService.CreateArticle:output_type -> article.v1.ReplyCreateArticle
	10, // 11: article.v1.ArticleService.UpdateArticle:output_type -> google.protobuf.Empty
	10, // 12: article.v1.ArticleService.DeleteArticle:output_type -> google.protobuf.Empty
	6,  // 13: article.v1.ArticleService.QueryArticle:output_type -> article.v1.ReplyQueryArticle
	8,  // 14: article.v1.ArticleService.ArticleList:output_type -> article.v1.ReplyArticleList
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_v1_proto_article_proto_init() }
func file_v1_proto_article_proto_init() {
	if File_v1_proto_article_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_proto_article_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCreateArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_article_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyCreateArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_article_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestUpdateArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_article_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDeleteArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_article_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestQueryArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_article_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyQueryArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_article_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestArticleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_article_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyArticleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_article_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticleItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_proto_article_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_proto_article_proto_goTypes,
		DependencyIndexes: file_v1_proto_article_proto_depIdxs,
		EnumInfos:         file_v1_proto_article_proto_enumTypes,
		MessageInfos:      file_v1_proto_article_proto_msgTypes,
	}.Build()
	File_v1_proto_article_proto = out.File
	file_v1_proto_article_proto_rawDesc = nil
	file_v1_proto_article_proto_goTypes = nil
	file_v1_proto_article_proto_depIdxs = nil
}
