// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: v2/proto/stream_demo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *InputStreamRequest) Reset() {
	*x = InputStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_proto_stream_demo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputStreamRequest) ProtoMessage() {}

func (x *InputStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_proto_stream_demo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputStreamRequest.ProtoReflect.Descriptor instead.
func (*InputStreamRequest) Descriptor() ([]byte, []int) {
	return file_v2_proto_stream_demo_proto_rawDescGZIP(), []int{0}
}

func (x *InputStreamRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type OutputStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *OutputStreamRequest) Reset() {
	*x = OutputStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_proto_stream_demo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputStreamRequest) ProtoMessage() {}

func (x *OutputStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_proto_stream_demo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputStreamRequest.ProtoReflect.Descriptor instead.
func (*OutputStreamRequest) Descriptor() ([]byte, []int) {
	return file_v2_proto_stream_demo_proto_rawDescGZIP(), []int{1}
}

func (x *OutputStreamRequest) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *OutputStreamRequest) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type BidirectionalStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *BidirectionalStreamRequest) Reset() {
	*x = BidirectionalStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_proto_stream_demo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidirectionalStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidirectionalStreamRequest) ProtoMessage() {}

func (x *BidirectionalStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_proto_stream_demo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidirectionalStreamRequest.ProtoReflect.Descriptor instead.
func (*BidirectionalStreamRequest) Descriptor() ([]byte, []int) {
	return file_v2_proto_stream_demo_proto_rawDescGZIP(), []int{2}
}

func (x *BidirectionalStreamRequest) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BidirectionalStreamRequest) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type DataReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data int64 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DataReply) Reset() {
	*x = DataReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_proto_stream_demo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataReply) ProtoMessage() {}

func (x *DataReply) ProtoReflect() protoreflect.Message {
	mi := &file_v2_proto_stream_demo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataReply.ProtoReflect.Descriptor instead.
func (*DataReply) Descriptor() ([]byte, []int) {
	return file_v2_proto_stream_demo_proto_rawDescGZIP(), []int{3}
}

func (x *DataReply) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

var File_v2_proto_stream_demo_proto protoreflect.FileDescriptor

var file_v2_proto_stream_demo_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0x2a, 0x0a, 0x12,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x31, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79, 0x22, 0x38, 0x0a, 0x1a, 0x42,
	0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x01, 0x79, 0x22, 0x1f, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x9d, 0x02, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x44, 0x65, 0x6d, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0b,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x22, 0x2e, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x28, 0x01, 0x12, 0x52,
	0x0a, 0x0c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x23,
	0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x62, 0x0a, 0x13, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x2a, 0x2e, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x6f, 0x2d, 0x6e, 0x6f, 0x74,
	0x65, 0x73, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76,
	0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v2_proto_stream_demo_proto_rawDescOnce sync.Once
	file_v2_proto_stream_demo_proto_rawDescData = file_v2_proto_stream_demo_proto_rawDesc
)

func file_v2_proto_stream_demo_proto_rawDescGZIP() []byte {
	file_v2_proto_stream_demo_proto_rawDescOnce.Do(func() {
		file_v2_proto_stream_demo_proto_rawDescData = protoimpl.X.CompressGZIP(file_v2_proto_stream_demo_proto_rawDescData)
	})
	return file_v2_proto_stream_demo_proto_rawDescData
}

var file_v2_proto_stream_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v2_proto_stream_demo_proto_goTypes = []interface{}{
	(*InputStreamRequest)(nil),         // 0: stream_demo.v1.InputStreamRequest
	(*OutputStreamRequest)(nil),        // 1: stream_demo.v1.OutputStreamRequest
	(*BidirectionalStreamRequest)(nil), // 2: stream_demo.v1.BidirectionalStreamRequest
	(*DataReply)(nil),                  // 3: stream_demo.v1.DataReply
}
var file_v2_proto_stream_demo_proto_depIdxs = []int32{
	0, // 0: stream_demo.v1.StreamDemoService.InputStream:input_type -> stream_demo.v1.InputStreamRequest
	1, // 1: stream_demo.v1.StreamDemoService.OutputStream:input_type -> stream_demo.v1.OutputStreamRequest
	2, // 2: stream_demo.v1.StreamDemoService.BidirectionalStream:input_type -> stream_demo.v1.BidirectionalStreamRequest
	3, // 3: stream_demo.v1.StreamDemoService.InputStream:output_type -> stream_demo.v1.DataReply
	3, // 4: stream_demo.v1.StreamDemoService.OutputStream:output_type -> stream_demo.v1.DataReply
	3, // 5: stream_demo.v1.StreamDemoService.BidirectionalStream:output_type -> stream_demo.v1.DataReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_proto_stream_demo_proto_init() }
func file_v2_proto_stream_demo_proto_init() {
	if File_v2_proto_stream_demo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v2_proto_stream_demo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_proto_stream_demo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_proto_stream_demo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidirectionalStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v2_proto_stream_demo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v2_proto_stream_demo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_proto_stream_demo_proto_goTypes,
		DependencyIndexes: file_v2_proto_stream_demo_proto_depIdxs,
		MessageInfos:      file_v2_proto_stream_demo_proto_msgTypes,
	}.Build()
	File_v2_proto_stream_demo_proto = out.File
	file_v2_proto_stream_demo_proto_rawDesc = nil
	file_v2_proto_stream_demo_proto_goTypes = nil
	file_v2_proto_stream_demo_proto_depIdxs = nil
}
